name: triplan
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
